/* Casos del simulador de tiroides. Los datos tecnicos salieron de los DICOM entregados a los
   estudiantes; cada archivo se reconoce por el hash FNV-1a de sus pixeles. La clinica esta
   desidentificada. La impresion del informe se muestra al terminar el caso. */
'use strict';
const TIRO_VISTAS=['ANTERIOR','ANTERIOR MARCA','OAD','OAI']; // orden de la panoramica del equipo
const TIRO_NOMBRE_VISTA={'ANTERIOR':'Anterior','ANTERIOR MARCA':'Anterior con marcas','OAD':'Oblicua anterior derecha','OAI':'Oblicua anterior izquierda'};
const TIRO_MARCAS=['mentón','horquilla esternal'];
const TIRO_PREGUNTAS_ORALES=[
 {titulo:'Indicación y radiofármaco',segundos:90,
  pregunta:'¿Qué pregunta clínica traen tus dos casos y qué responde un cintigrama tiroideo que no responde la ecografía? Explica cómo entra el pertecnetato a la tiroides, en qué se parece y en qué se diferencia del yodo, y por qué también se ven las glándulas salivales.',
  preparar:'Usa el antecedente de cada caso y revisa el radiofármaco y la ventana energética en «Información de la adquisición». Distingue lo que consta en el DICOM de lo que dice el antecedente.'},
 {titulo:'Adquisición y formación de imagen',segundos:120,
  pregunta:'Compara la anterior de un caso con la del otro: matriz, zoom, píxel, cuentas y duración. ¿Por qué duraron distinto si el criterio de paro fue el mismo? ¿Qué gana y qué pierde el zoom de adquisición frente al zoom que aplicas en la página?',
  preparar:'Lee la duración y las cuentas de cada archivo en el paso 1. El paro fue por cuentas; la duración es la consecuencia de la captación y de la dosis.'},
 {titulo:'Marcas y referencias anatómicas',segundos:120,
  pregunta:'¿Para qué se adquiere una segunda anterior con fuentes puntuales en el mentón y la horquilla esternal? Muestra en tu página dónde quedaron las marcas y qué te permiten decir de la posición de la glándula. ¿Qué pasa si la marca se mueve entre imágenes?',
  preparar:'Señala las dos flechas que anotaste. Explica cómo distinguiste una marca de un foco de captación real y por qué no midiste tamaños sobre la imagen.'},
 {titulo:'Lectura de las imágenes',segundos:180,
  pregunta:'Para cada caso: tamaño y forma de la glándula, captación global frente al fondo y a las salivales, focos hiper o hipocaptantes y qué aportan las oblicuas. Distingue bocio difuso, nódulo caliente con supresión del resto y nódulo frío. Describe sin asumir la causa por el antecedente.',
  preparar:'Un minuto y medio por caso sobre tu página. Usa las oblicuas para separar lo que se superpone en la anterior. Reconoce lo que no puedes afirmar sin ecografía ni laboratorio.'},
 {titulo:'Decisiones de presentación y control de calidad',segundos:90,
  pregunta:'Justifica una decisión propia de cada caso: ventana, zoom, encuadre, orden de las imágenes o rótulos. ¿Qué cambia en la lectura si la ventana quema la tiroides o si el encuadre corta las salivales? ¿Qué revisarías antes de enviar la página al PACS?',
  preparar:'Anota el techo y el zoom que usaste en cada imagen. La página exportada es lo que verá el médico: encabezado, rótulos y marcas tienen que poder leerse proyectados.'}
];
const TIRO_CASOS={
 1:{titulo:'Nódulo tóxico derecho con supresión del resto',resumen:'El caso de referencia del nódulo autónomo: un solo foco intenso y el resto de la glándula apagado.',
  clinica:{antecedentes:'56 años. Hipertiroidismo.',procedimiento:'Tc-99m pertecnetato, 11,5 mCi por vía endovenosa. Proyecciones anterior con marcas en mentón y horquilla esternal, anterior y oblicuas anteriores.'},
  particularidades:['El nódulo ocupa casi todo el lóbulo derecho y suprime el resto: con el techo de la escala al máximo verás solo el nódulo. Baja el techo para mostrar lo que queda de glándula y el fondo.','El fondo circulante está disminuido: la glándula se lleva el trazador.'],
  preguntas:['¿Por qué un nódulo autónomo apaga el resto de la glándula? Relaciona TSH, captación y la imagen.','Con el techo al 100 % solo se ve el nódulo. ¿Qué ventana elegiste para la página y por qué esa es una decisión que cambia la lectura?','¿Qué verías en este paciente con yodo radiactivo en vez de pertecnetato? ¿Cambiaría la indicación de tratamiento?','Las oblicuas: ¿qué agregan cuando la anterior ya muestra el nódulo?'],
  referencia:{impresion:'Estudio compatible con nódulo tóxico hipertiroideo derecho.'},
  archivos:{'ANTERIOR':'1ed80817','ANTERIOR MARCA':'ea4263ec','OAD':'7f83a571','OAI':'465cdfb8'}},
 2:{titulo:'Bocio difuso hiperfuncionante, Graves',resumen:'Glándula grande, captación intensa y simétrica, fondo bajo. Adquisiciones de un minuto.',
  clinica:{antecedentes:'32 años. Hipertiroidismo. Enfermedad de Graves. Ecografía: bocio difuso con signos de tiroiditis y nódulo ístmico hiperecogénico TIRADS 3.',procedimiento:'Tc-99m pertecnetato, 13,3 mCi por vía endovenosa. Planares cervicales anteriores con y sin marcas, y oblicuas anteriores.'},
  particularidades:['Las cuatro imágenes duraron unos 60 segundos: la glándula capta tanto que llegó a las 500 kcuentas en un minuto. Compáralo con el caso 5.','El nódulo de la ecografía no se ve: la captación difusa lo esconde. Es un buen ejemplo de lo que el cintigrama no puede resolver.'],
  preguntas:['¿Por qué las adquisiciones duraron un minuto y en otros casos cuatro? ¿Qué te dice eso antes de mirar la imagen?','El nódulo TIRADS 3 de la ecografía no tiene correlato cintigráfico. ¿Por qué, y qué le dirías al clínico?','Fondo bajo y salivales tenues frente a la tiroides: ¿qué mecanismo explica esa relación en Graves?','¿Qué diferencia esperarías entre este bocio difuso y una tiroiditis subaguda en la imagen?'],
  referencia:{impresion:'Bocio difuso hiperfuncionante, en concordancia con el antecedente, sin evidencias claras de focos hiper o hipocaptantes. El nódulo descrito en ecografía no tiene claro correlato cintigráfico por la intensa captación del parénquima.'},
  archivos:{'ANTERIOR':'8ddeb693','ANTERIOR MARCA':'527d535c','OAD':'bfd6701d','OAI':'e5c20615'}},
 3:{titulo:'Foco levemente hipercaptante, no autónomo',resumen:'Glándula normal con un lóbulo derecho un poco más activo; la imagen con marcas se cortó a los 39 segundos.',
  clinica:{antecedentes:'Síndrome crónico en estudio. Nódulos tiroideos derecho e izquierdo.',procedimiento:'Tc-99m pertecnetato, 9,2 mCi por vía endovenosa. Planares cervicales anteriores con y sin marcas, y oblicuas anteriores.'},
  particularidades:['La anterior con marcas tiene 144 kcuentas en 39 segundos, la tercera parte de las demás: se interrumpió. Es más ruidosa; ajústale la ventana aparte y dilo en la presentación.','La diferencia entre lóbulos es sutil y se ve mejor en la oblicua izquierda.'],
  preguntas:['La imagen con marcas se cortó a los 39 segundos. ¿Cómo lo notaste, cómo la presentaste y qué habrías hecho en el equipo?','Un foco «levemente hipercaptante, no autónomo»: ¿qué lo distingue de un nódulo tóxico en la imagen?','¿Por qué el informe manda a correlacionar con ecografía y no al revés?','Con dos nódulos conocidos y una imagen casi simétrica, ¿qué puede y qué no puede decir el cintigrama?'],
  referencia:{impresion:'Foco levemente hipercaptante en el lóbulo tiroideo derecho, no autónomo, que puede corresponder al nódulo conocido; correlacionar con ecotomografía. Sin otros focos ni signos indirectos de hiperfunción.'},
  archivos:{'ANTERIOR':'a46f36cd','ANTERIOR MARCA':'c162f66f','OAD':'768f9730','OAI':'faa2f48c'}},
 4:{titulo:'El caso normal',resumen:'Glándula de tamaño normal y captación conservada, sin focos. Sirve de patrón para los demás.',
  clinica:{antecedentes:'Hipertiroidismo subclínico. Ecografía con nódulos tiroideos bilaterales y nódulo dominante inferior izquierdo.',procedimiento:'Tc-99m pertecnetato, dosis estándar. Planares cervicales anteriores y oblicuas.'},
  particularidades:['Es el caso normal del set: úsalo como referencia de forma, tamaño y relación con las salivales.','Los nódulos de la ecografía no se representan: la ecografía ve estructura, el cintigrama ve función.'],
  preguntas:['Describe una tiroides normal en el cintigrama: forma, lóbulos, istmo, relación con salivales y fondo.','Hipertiroidismo subclínico con cintigrama normal: ¿es contradictorio? ¿Qué mide cada cosa?','¿Por qué los nódulos ecográficos no siempre se ven? ¿Qué tamaño mínimo tendría que tener un nódulo frío para verse?','¿Qué aportan las oblicuas en un caso normal?'],
  referencia:{impresion:'Cintigrama tiroideo dentro de límites normales. El nódulo descrito en ecografía no tiene clara representación cintigráfica.'},
  archivos:{'ANTERIOR':'13c9ce1f','ANTERIOR MARCA':'6b93bff4','OAD':'a67c4711','OAI':'46f256ef'}},
 5:{titulo:'Bocio multinodular con dos nódulos calientes',resumen:'Glándula grande con nódulos hiperfuncionantes bilaterales, el dominante inferior izquierdo, y el resto heterogéneo.',
  clinica:{antecedentes:'Bocio multinodular. Hipertiroidismo.',procedimiento:'Tc-99m pertecnetato, 10,2 mCi por vía endovenosa. Estáticas cervicales anteriores y oblicuas anteriores, incluida una imagen con fuente puntual externa en la escotadura esternal.'},
  particularidades:['Las adquisiciones son las más largas del set, hasta 248 segundos: la dosis se reparte en una glándula grande y heterogénea.','Hay dos nódulos calientes, uno a cada lado, y zonas frías entre ellos: el encuadre y el zoom deciden si se ven todos.'],
  preguntas:['¿Cómo distingues en la imagen un nódulo caliente de parénquima sano suprimido, y un nódulo frío de un espacio entre nódulos?','El dominante está en el polo inferior izquierdo. ¿Qué oblicua lo separa mejor y por qué?','Adquisiciones de cuatro minutos frente al minuto del caso 2: ¿qué dice eso de la captación global?','Bocio multinodular tóxico frente a Graves: ¿qué cambia en el tratamiento con yodo radiactivo y por qué importa la imagen?'],
  referencia:{impresion:'Hallazgos sugerentes de bocio multinodular con nódulos hiperfuncionantes bilaterales, el dominante en el polo inferior del lóbulo izquierdo.'},
  archivos:{'ANTERIOR':'00935627','ANTERIOR MARCA':'f5857dba','OAD':'cd0b8a2f','OAI':'86ef4611'}},
 6:{titulo:'Bocio difuso hiperfuncionante, captación irregular',resumen:'Tirotoxicosis con glándula levemente aumentada, captación alta y algo irregular, sin focos netos.',
  clinica:{antecedentes:'73 años. Tirotoxicosis.',procedimiento:'Tc-99m pertecnetato, 14,7 mCi por vía endovenosa. Proyecciones anterior con marcas en mentón y horquilla esternal, anterior y oblicuas anteriores.'},
  particularidades:['La captación es irregular pero sin focos: la ventana decide si esa irregularidad parece nódulos o no. Cuidado con exagerar el contraste.','Compara con el caso 2: mismo diagnóstico, distinta edad y distinta textura.'],
  preguntas:['¿Qué diferencia una captación «levemente irregular» de un patrón multinodular? ¿Cómo lo decidiste en tu ventana?','Tirotoxicosis en una paciente de 73 años: ¿qué diagnósticos diferenciales tiene y cuál favorece esta imagen?','Fondo circulante disminuido: ¿qué significa y cómo lo verificaste en la imagen?','¿Qué papel juega la dosis administrada en la calidad de la imagen y la duración?'],
  referencia:{impresion:'Estudio compatible con bocio difuso hiperfuncionante.'},
  archivos:{'ANTERIOR':'5d7492ae','ANTERIOR MARCA':'ce046025','OAD':'a146e162','OAI':'9f6f0dac'}},
 7:{titulo:'Tiroides tenue, salivales dominantes (sin informe)',resumen:'Glándula pequeña y de baja captación frente a unas salivales muy visibles. No hay informe: la lectura es tuya.',
  clinica:{antecedentes:'No hay informe ni antecedente disponible para este caso. Lee las imágenes con lo que ves y con lo que sabes de la asignatura.',procedimiento:'Tc-99m pertecnetato. Proyecciones anterior con y sin marcas y oblicuas anteriores, en el mismo protocolo de los demás casos.'},
  particularidades:['Sin informe: al terminar no habrá impresión con la que comparar. Tu descripción y tu hipótesis son el producto.','La tiroides capta poco y las glándulas salivales y la mucosa dominan la imagen. Con el techo al máximo la tiroides casi desaparece: elige la ventana pensando en qué quieres mostrar.','Las 500 kcuentas se juntaron en 85 segundos, pero no por la tiroides: por todo lo demás.'],
  preguntas:['Una tiroides tenue con salivales intensas: ¿qué causas conoces? Piensa en tiroiditis, bloqueo por yodo o medicamentos, hormona exógena.','¿Qué dato de laboratorio o de historia pedirías primero para decidir entre esas causas?','¿Cómo presentaste una glándula que casi no se ve sin quemar el resto de la imagen?','¿Qué escribirías tú como impresión, con qué grado de certeza, y qué recomendarías?'],
  referencia:null,
  archivos:{'ANTERIOR':'dadb7c78','ANTERIOR MARCA':'90f8da1d','OAD':'687b55ff','OAI':'dcef6344'}},
 8:{titulo:'Nódulo frío inferior izquierdo',resumen:'Glándula normal con un área hipocaptante de unos 11 × 12 mm en el tercio inferior izquierdo. Las oblicuas quedaron registradas a 180°.',
  clinica:{antecedentes:'Nódulo tiroideo izquierdo en estudio.',procedimiento:'Tc-99m pertecnetato. Planares cervicales anteriores y oblicuas anteriores, con y sin marca.'},
  particularidades:['Los ángulos registrados de las oblicuas son 180°, iguales a la anterior, aunque las imágenes sí son oblicuas: el rótulo lo eligió el operador, el ángulo no se actualizó. Compara con el caso 1.','El nódulo frío es pequeño: la ventana y el zoom deciden si se ve. No lo midas sobre la imagen; la ecografía lo hará.'],
  preguntas:['¿Por qué un nódulo frío importa más que uno caliente en el manejo clínico?','Las oblicuas dicen 180° en la cabecera. ¿Cómo sabes que son oblicuas y qué implica para confiar en los rótulos?','El informe dice «aproximadamente 11 × 12 mm». ¿Por qué no conviene medir tamaños en una imagen planar de gammacámara?','¿Qué ventana muestra mejor un defecto frío pequeño: estrecha o amplia? Justifícalo con tu página.'],
  referencia:{impresion:'Foco hipocaptante en el tercio inferior del lóbulo izquierdo, sugerente de nódulo hipocaptante; correlacionar con ecotomografía. Sin otros focos ni signos indirectos de hiperfunción.'},
  archivos:{'ANTERIOR':'00329e59','ANTERIOR MARCA':'0b50c2ee','OAD':'4999b9ea','OAI':'3b2d819a'}},
 9:{titulo:'Nódulo derecho levemente hipercaptante',resumen:'Lóbulo derecho aumentado por un área ovoidea un poco más activa que el resto; parénquima restante normal.',
  clinica:{antecedentes:'Bocio multinodular. Hipertiroidismo subclínico.',procedimiento:'Tc-99m pertecnetato, dosis habitual. Imágenes planares cervicales a los 10 minutos, incluida una con fuente radiactiva externa en la escotadura supraesternal.'},
  particularidades:['La diferencia entre el nódulo y el parénquima es leve: una ventana muy contrastada la exagera y una muy amplia la borra. Busca el punto medio y explícalo.','El informe menciona que las imágenes se tomaron a los 10 minutos de la inyección.'],
  preguntas:['¿Qué diferencia un nódulo «levemente hipercaptante» de uno autónomo? ¿Qué pasa con el resto de la glándula en cada caso?','¿Por qué se adquiere a los 10 o 20 minutos y no de inmediato ni a las 3 horas como el DMSA?','¿Cómo mostraste una diferencia leve sin exagerarla? Explica tu ventana.','Bocio multinodular con hipertiroidismo subclínico: ¿qué le aporta este estudio al endocrinólogo?'],
  referencia:{impresion:'Hallazgos compatibles con un nódulo tiroideo derecho levemente hipercaptante.'},
  archivos:{'ANTERIOR':'c96ac790','ANTERIOR MARCA':'f05c8795','OAD':'d8cf2313','OAI':'b98924ca'}},
 10:{titulo:'Hemitiroidectomía y nódulo autónomo',resumen:'Solo queda el lóbulo derecho, y en él un nódulo intensamente hipercaptante sin parénquima normal visible.',
  clinica:{antecedentes:'Observación de nódulo autónomo en el lóbulo tiroideo derecho.',procedimiento:'Tc-99m pertecnetato, 16,1 mCi. Planares cervicales anteriores y oblicuas.'},
  particularidades:['Falta el lóbulo izquierdo: hay una hemitiroidectomía. No lo confundas con un lóbulo suprimido; usa las marcas para ubicar la línea media.','El nódulo es lo único que capta: con el techo al máximo la página muestra un solo punto. Decide qué más quieres que se vea.'],
  preguntas:['¿Cómo distingues en la imagen un lóbulo ausente por cirugía de un lóbulo suprimido por un nódulo autónomo contralateral? ¿Qué papel juegan las marcas?','Un nódulo autónomo en el único lóbulo que queda: ¿qué opciones de tratamiento cambia eso?','Dosis de 16,1 mCi, la más alta del set, y adquisiciones de 70 segundos: ¿cómo se relacionan?','¿Qué muestra tu página que la del equipo no, o al revés?'],
  referencia:{impresion:'Nódulo significativamente hipercaptante en el lóbulo tiroideo derecho, compatible con nódulo autónomo. Hemitiroidectomía izquierda, sin captación en parénquima tiroideo normal.'},
  archivos:{'ANTERIOR':'43f994e0','ANTERIOR MARCA':'e9794960','OAD':'e4d6d558','OAI':'e3625e49'}}
};
function tiroReconocer(hash){for(const [n,c] of Object.entries(TIRO_CASOS))for(const [vista,h] of Object.entries(c.archivos))if(h===hash)return {caso:Number(n),vista};return null;}
